version: '3'
services:
#  myapplication:
#    image: mongodb/mongodb-community-server:6.0-ubi8
#    environment:
#      - CONN_STR=mongodb://user:pass@mongodb
#    command: '/bin/bash -c "sleep 5; mongosh $$CONN_STR --eval \"show dbs;\""'
#    depends_on:
#      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: stocks1234
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
