version: '3.8'
services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=stocks
      - MYSQL_USER=stocks
      - MYSQL_PASSWORD=1234
    ports:
      - "3306:3306"
volumes:
  mysql-data: