spring:

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  data:
    mongodb:
      uri: mongodb://root:password@localhost:27017/mydatabase?authSource=admin

  application:
    name: Investment-Management

  jackson:
    serialization:
      INDENT_OUTPUT: true

  output:
    ansi:
      enabled: always



logging:
  level:
    root: info

  file:
    name: logs/application.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"

server:
  servlet:
    session:
      timeout: 2m

alphavantage:
  api:
    key: 6FZME81OT4D69JJV
    url: https://www.alphavantage.co/query